version: '3'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    volumes:
      - ./app:/app
