from db.controllers.category_ai import *
from db.controllers.history_message import *
from db.controllers.package import *
from db.controllers.person_ai import *
from db.controllers.person_ai_skill import *
from db.controllers.skills import *
from db.controllers.user_person_ai import *
from db.controllers.user import *
from db.controllers.config import *
from db.controllers.config_set import *
from db.controllers.history_message_report import *
from db.controllers.report_per_message import *
from db.controllers.parent import *
from db.controllers.draw_style import *
from db.controllers.link_request import *
from db.controllers.notification_template import *
from db.controllers.notification import *
from db.controllers.package_group import *
from db.controllers.app_report import *
from db.controllers.language import *
from db.controllers.user_progress_tracking import *
from db.controllers.mail import *
from db.controllers.utils import *
